### ISSUE TITLE
Joyride positioned off the screen

### ISSUE THREAD

**Issue by steve-tapley** [ahmed-wagdi/angular-joyride#13]
Hi,

We're wanting to create a joyride that is attached to an element on the far left of the screen.   However, when we do this, the joyride is actually positioned half off the screen - making it unusable

Heres is a plunkr demonstrating the issue:
https://plnkr.co/edit/OoLvv5X6yQuHFYT0dyi5

Cheers,
Steve

**Comment by ahmed-wagdi** [comment]
I made some changes to re-adjust the joyride's position if it's offscreen. Update the package and try again.

If you're still having problems let me know.

**Comment by steve-tapley** [comment]
Hi Ahmed,
Great job - it works perfectly!
Cheers,
Steve
