### ISSUE TITLE
Joyride positioned offscreen (#2)

### ISSUE THREAD

**Issue by steve-tapley** [ahmed-wagdi/angular-joyride#14]
Hi,
This is related to #13 , but now an item at the top is off the screen

See the plunkr for an example:
https://plnkr.co/edit/WUKd9diJaCoeJbhwjLWe?p=preview

Cheers,
Steve

**Comment by ahmed-wagdi** [comment]
Alright that shouldn't be a problem to fix but it might take me a few days to get to it.

**Comment by steve-tapley** [comment]
My hacky fix for this was in the setPos() function, approx line 328

`if (position.top < 0) {
   var triangle = document.querySelector(".jr_container .triangle");
   triangle.style.top = (position.top * 2) + 'px';
   position.top = 0;
}`

**Comment by ahmed-wagdi** [comment]
Updated the package, it should be working now.
