### ISSUE TITLE
The joyride's popup does not work

### ISSUE THREAD

**Issue by FloMaetschke** [ahmed-wagdi/angular-joyride#3]
Any idea why the joyrides text is displayed at the end of the page instead inside the popup ?

I have included the css.

**Comment by ahmed-wagdi** [comment]
I need more information to be able to help you. Are you sure you're including the directive correctly in your application and are you getting any errors?

Seeing some code would help.

**Comment by FloMaetschke** [comment]
It was my fault. sass wasn't able to import .css file. 
Thx! everything is working now.

**Comment by ahmed-wagdi** [comment]
ok great

**Comment by mrinalinihanagodu** [comment]
Hi, I am facing the same issue, could someone help

**Comment by ahmed-wagdi** [comment]
@mrinalinihanagodu this issue was caused by not including the css for the joyride correctly, check if that's also the case for you or not. If not then show me a screenshot of the problem and check for errors in the console.
