### ISSUE TITLE
Popup is scroll to the top of page, causing some of the highlighted content to overflow from the screen

### ISSUE THREAD

**Issue by cjb5333** [ahmed-wagdi/angular-joyride#4]
Your directive is very helpful - helped me escape a jquery dependency on other directive :)

When using left and right positions, the popup scrolls to top; however, since the popup is centered on the element and the top of the element extends past the top of the popup, it is cut off the screen.

I'm not sure if i'm doing something wrong or if this should be an issue, thanks!

**Comment by ahmed-wagdi** [comment]
I'm glad you found it helpful :)

Could you send a screenshot of the problem?

**Comment by cjb5333** [comment]
I took 2 screenshots, but had to remove any PI.

This is the full element, and how I would expect it to be position with respect to the top of the page. In this screenshot, the top of the image is the top of the screen:
![angular-joyride_good](https://cloud.githubusercontent.com/assets/1859325/21942432/171b6006-d99b-11e6-9f0f-95e3eca082e2.png)

This is the screenshot of how it actually renders and where it scrolls to. Again, the top of the image is the top of the screen, and you can see that the top part of the element from the previous screenshot is hidden and off the page:
![angular-joyride_bad](https://cloud.githubusercontent.com/assets/1859325/21942464/4341e51a-d99b-11e6-8d53-3558bbd4708c.png)

**Comment by ahmed-wagdi** [comment]
So you're saying that the the window scrolls to the top of the joyride popup but it should be scrolling to the top of the highlighted element instead correct?

If that's the case then i'm not really getting the same issue, i created a plunkr here where it seems to be working fine: https://plnkr.co/edit/OagapaIJ5GxO1QKHTqNj?p=preview
